name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --all --release
      - name: Build Docker image
        run: docker build -t planter:latest .
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag planter:latest queuetue/planter:latest
          docker push queuetue/planter:latest
